---
- name: copy compose-file - {{appname}}
  template:
    src: "docker-compose.{{appname}}.yml.j2"
    dest: "{{docker_compose_path}}/docker-compose.yml"
    mode: 0600
  tags:
    - config
    - reconfigure
