---
- name: copy compose-file - psql
  template:
    src: "docker-compose.psql.yml.j2"
    dest: "{{docker_compose_path}}/docker-compose.yml"
    mode: 0600
  tags:
    - config
    - reconfigure

- name: run restart compose
  shell: "docker-compose down && docker-compose up -d"
  args:
    chdir: "{{docker_compose_path}}"
