---
- import_tasks: 10-install-docker-compose-centos.yml
  when: ansible_distribution == 'CentOS'
  tags:
    - docker-compose
    - docker

- import_tasks: 20-install-docker-compose-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags:
    - docker-compose
    - docker