# Generated by Django 3.0.8 on 2022-05-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='берите автора', to='catalog.Author', verbose_name='Автор книги'),
        ),
    ]
