apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web2-deployment
  labels:
    app: my-k8s2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: devops2
  template:
    metadata:
      labels:
        project: devops2
    spec:
      containers:
        - name: devops2-web
          image: idelfazletdinov/k8sphp:version2
          ports:
            - containerPort: 80   
