apiVersion: v1
kind: Service
metadata:
  name: my-single-pod2-service
  labels:
    env  : prod
    owner: IdelFazletdinov
spec:
  type: LoadBalancer
  selector:
    project: devops2
  ports:
    - name      : app2-listener
      protocol  : TCP
      port      : 80
      targetPort: 80
