apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web1-deployment
  labels:
    app: my-k8s1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: devops1
  template:
    metadata:
      labels:
        project: devops1
    spec:
      containers:
        - name: devops1-web
          image: idelfazletdinov/k8sphp:version1
          ports: 
            - containerPort: 80
