---

- name: install programs
  hosts: all
  become: yes
  
  tasks: 
  - name: install group programs for RedHat
    yum: 
      name: "{{ package }}"
    vars: 
      package:
      - mc
      - wget
      - tar
      state: latest
    when: ansible_os_family == "RedHat"

  - name: install group programs for Debian
    apt: 
      name: "{{ package }}"
    vars: 
      package:
      - mc
      - wget
      - tar
      state: latest
    when: ansible_os_family == "Debian"
      
