---

- name: Удалим пользователей на удаленных серверах
  hosts: all
  become: yes
  
  tasks: 
  - name: Удалим пользователя bomjur с удаленных серверов
    ansible.builtin.user:
      name: bomjur
      state: absent
      remove: yes
   
  - name: Удалим пользователя sharik с удаленных серверов
    ansible.builtin.user:
      name: sharik
      state: absent
      remove: yes
