apiversion  : v2
name        : App-HelmChart
description : My Helm chart for Kubernetes
type        : application
version     : 3.8.1
appVersion  : "1.2.3"

keywords:
  - apache
  - http
  - https
  - idelfazletdinov

maintainers:
  - name : Idel Fazletdinov
    email: fvi-it@mail,ru
    url  : www.fazletdinov.com

